codestates-seb/seb39_main_038

.gitignore
LICENSE
frontend/.eslintrc.json
frontend/.husky/pre-commit
frontend/.prettierrc.json
frontend/babel.config.js
frontend/netlify.toml
frontend/package-lock.json
frontend/package.json
frontend/public/index.html
frontend/src/App.js
frontend/src/index.css
frontend/src/index.js
frontend/webpack.config.js
server/app.js
server/package-lock.json
server/package.json

feat: 프론트엔드 기본 설정 완료

---

src/main/resources/application.yml

fix: 경로 지정후 빌드

---

.github/workflows/gradle.yml

feat : crud test를 위한 PR

---

.github/workflows/gradle.yml
.gitignore
src/main/resources/application.yml

feat: crud 테스트를 위한 PR

---

build.gradle

feat: crud test를 위한 PR

---

.github/workflows/gradle.yml

fix: gradle.yml 파일 mysql 설정 추가

fix: gradle.yml 파일 mysql 설정 추가

---

src/test/java/com/main_39/Spring/ApplicationTests.java

fix: 빌드 오류나는 부분

---

frontend/src/components/DetailMenuBar/atom.js
frontend/src/components/DetailMenuBar/index.js
frontend/src/components/DetailMenuBar/styles.js
frontend/src/index.js
frontend/src/pages/FoodList/Detailstyles.js
frontend/src/pages/FoodList/FoodDetail.js
frontend/src/style/theme.js

FoodDetail 클린리뷰 CSS 구성 완료
브랜치를 업데이트하고 깃풀을 하여 git conflict 발생 수정하다 꼬여서 로컬 브랜치 삭제 후 다시 받아서 재업함.
CSS 푸드트럭 위에 빈공간이 남아 찾아 수정할 예정

Design: FoodDetail 클린리뷰 CSS 구성 완료

---

src/main/java/com/main_39/Spring/exception/ExceptionCode.java
src/main/java/com/main_39/Spring/menu/Menu.java
src/main/java/com/main_39/Spring/menu/MenuController.java
src/main/java/com/main_39/Spring/menu/MenuPostRequestDto.java
src/main/java/com/main_39/Spring/menu/MenuRepository.java
src/main/java/com/main_39/Spring/order/Order.java
src/main/java/com/main_39/Spring/order/OrderController.java
src/main/java/com/main_39/Spring/order/OrderMenu.java
src/main/java/com/main_39/Spring/order/OrderMenuPostRequestDto.java
src/main/java/com/main_39/Spring/order/OrderPostRequestDto.java
src/main/java/com/main_39/Spring/order/OrderRepository.java
src/main/java/com/main_39/Spring/order/OrderService.java
src/test/java/com/main_39/Spring/ApiTest.http

feat: 주문, 메뉴 기능 추가

---

frontend/src/components/DetailMenuBar/atom.js
frontend/src/components/DetailMenuBar/index.js
frontend/src/components/DetailMenuBar/styles.js
frontend/src/pages/FoodList/FoodDetail.js
frontend/src/pages/FoodList/FoodDetailstyles.js

Design: FoodDetail 페이지 CSS 구성 완료

---

src/main/java/com/main_39/Spring/config/SecurityConfig.java
src/main/java/com/main_39/Spring/menu/controller/MenuController.java
src/main/java/com/main_39/Spring/menu/service/MenuService.java

메뉴 수정 기능 개선, 통신 테스트 cors 임시 해제

refactor: 메뉴 수정 기능 개선, 통신 테스트 cors 임시 해제

---

src/main/java/com/main_39/Spring/config/CorsConfig.java
src/main/java/com/main_39/Spring/config/SecurityConfig.java
src/main/java/com/main_39/Spring/menu/controller/MenuController.java
src/main/java/com/main_39/Spring/menu/service/MenuService.java

refactor:  localhost:3000 cors 해제

---

src/main/java/com/main_39/Spring/config/CorsConfig.java

feat: addExposedHeader 속성 추가

---

src/main/java/com/main_39/Spring/config/CorsConfig.java
src/main/java/com/main_39/Spring/config/filter/JwtAuthenticationFilter.java
src/main/java/com/main_39/Spring/config/filter/JwtAuthorizationFilter.java
src/main/java/com/main_39/Spring/member/controller/MemberController.java

fix: 도메인 주소 수정

---

src/main/java/com/main_39/Spring/config/CorsConfig.java
src/main/java/com/main_39/Spring/config/filter/JwtAuthenticationFilter.java
src/main/java/com/main_39/Spring/config/filter/JwtAuthorizationFilter.java
src/main/java/com/main_39/Spring/member/controller/MemberController.java

fix: domain 주소 수정

---

src/main/java/com/main_39/Spring/config/CorsConfig.java
src/main/java/com/main_39/Spring/config/SecurityConfig.java
src/main/java/com/main_39/Spring/config/filter/JwtAuthenticationFilter.java
src/main/java/com/main_39/Spring/config/filter/JwtAuthorizationFilter.java
src/main/java/com/main_39/Spring/config/oauth/LocalDetailsService.java
src/main/java/com/main_39/Spring/member/controller/MemberController.java
src/main/java/com/main_39/Spring/member/service/MemberService.java
src/main/java/com/main_39/Spring/store/entity/Store.java

필터, Security 클래스, Member패키지 하위 클래스들 Java Doc 추가하였습니다.

feat: java doc 추가, Store 엔티티, DTO추가

---

src/main/java/com/main_39/Spring/member/dto/LocalDto.java
src/main/java/com/main_39/Spring/review/controller/ReviewController.java
src/main/java/com/main_39/Spring/review/dto/ReviewPatchDto.java
src/main/java/com/main_39/Spring/review/dto/ReviewPostDto.java
src/main/java/com/main_39/Spring/review/dto/ReviewResponseDto.java
src/main/java/com/main_39/Spring/review/entity/Review.java
src/main/java/com/main_39/Spring/review/entity/ReviewSeller.java
src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java
src/main/java/com/main_39/Spring/review/repository/ReviewRepository.java
src/main/java/com/main_39/Spring/review/service/ReviewService.java
src/main/java/com/main_39/Spring/store/controller/StoreController.java
src/main/java/com/main_39/Spring/store/dto/StorePatchDto.java
src/main/java/com/main_39/Spring/store/dto/StorePostDto.java
src/main/java/com/main_39/Spring/store/dto/StoreResponseDto.java
src/main/java/com/main_39/Spring/store/entity/Store.java
src/main/java/com/main_39/Spring/store/mapper/StoreMapper.java
src/main/java/com/main_39/Spring/store/repository/StoreRepository.java
src/main/java/com/main_39/Spring/store/service/StoreService.java
src/main/resources/application-local.yml
src/main/resources/application-server.yml

feat : store, review 업로드

---

src/main/java/com/main_39/Spring/advice/ErrorResponse.java
src/main/java/com/main_39/Spring/exception/ExceptionCode.java
src/main/java/com/main_39/Spring/member/dto/LocalDto.java
src/main/java/com/main_39/Spring/review/controller/ReviewController.java
src/main/java/com/main_39/Spring/review/dto/ReviewPatchDto.java
src/main/java/com/main_39/Spring/review/dto/ReviewPostDto.java
src/main/java/com/main_39/Spring/review/dto/ReviewResponseDto.java
src/main/java/com/main_39/Spring/review/entity/Review.java
src/main/java/com/main_39/Spring/review/entity/ReviewSeller.java
src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java
src/main/java/com/main_39/Spring/review/repository/ReviewRepository.java
src/main/java/com/main_39/Spring/review/service/ReviewService.java
src/main/java/com/main_39/Spring/store/controller/StoreController.java
src/main/java/com/main_39/Spring/store/dto/StoreMenuPostDto.java
src/main/java/com/main_39/Spring/store/dto/StoreMenuResponseDto.java
src/main/java/com/main_39/Spring/store/dto/StorePatchDto.java
src/main/java/com/main_39/Spring/store/dto/StorePostDto.java
src/main/java/com/main_39/Spring/store/dto/StoreResponseDto.java
src/main/java/com/main_39/Spring/store/entity/Store.java
src/main/java/com/main_39/Spring/store/mapper/StoreMapper.java
src/main/java/com/main_39/Spring/store/repository/StoreRepository.java
src/main/java/com/main_39/Spring/store/service/StoreService.java
src/main/resources/application-local.yml
src/main/resources/application-server.yml

feat: store, review merge

---

build.gradle
src/main/java/com/main_39/Spring/store/controller/StoreController.java
src/main/java/com/main_39/Spring/store/repository/StoreRepository.java
src/main/java/com/main_39/Spring/store/service/S3Uploader.java
src/main/java/com/main_39/Spring/store/service/StoreService.java

feat: s3 이미지 업로드

---

src/main/java/com/main_39/Spring/comment/controller/CommentController.java
src/main/java/com/main_39/Spring/comment/dto/CommentPostDto.java
src/main/java/com/main_39/Spring/comment/dto/CommentResponseDto.java
src/main/java/com/main_39/Spring/comment/entity/Comment.java
src/main/java/com/main_39/Spring/comment/service/CommentService.java
src/main/java/com/main_39/Spring/member/mapper/MemberMapper.java
src/main/java/com/main_39/Spring/review/dto/ReviewStoreResponseDto.java
src/main/java/com/main_39/Spring/review/dto/ReviewsResponseDto.java
src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java
src/main/java/com/main_39/Spring/store/dto/StoreResponseDto.java
src/main/java/com/main_39/Spring/store/entity/Store.java

feat: review, store CRUD 추가

---

src/main/java/com/main_39/Spring/order/controller/OrderController.java
src/main/java/com/main_39/Spring/order/dto/OrderDetailResponse.java
src/main/java/com/main_39/Spring/order/dto/OrderRequest.java
src/main/java/com/main_39/Spring/order/dto/OrderResponse.java
src/main/java/com/main_39/Spring/order/entity/Order.java
src/main/java/com/main_39/Spring/order/entity/PaymentType.java
src/main/java/com/main_39/Spring/order/mapper/OrderMapper.java

feat: 주문 기능 결제 타입 추가

---

src/main/java/com/main_39/Spring/member/dto/KakaoDto.java
src/main/java/com/main_39/Spring/member/mapper/MemberMapper.java

remove: 카카오 마이페이지 -> 주문내역 출력 삭제

---

src/main/java/com/main_39/Spring/order/controller/OrderController.java
src/main/java/com/main_39/Spring/order/dto/OrderDetailResponse.java
src/main/java/com/main_39/Spring/order/dto/OrderRequest.java
src/main/java/com/main_39/Spring/order/dto/OrderResponse.java
src/main/java/com/main_39/Spring/order/dto/OrdersResponse.java
src/main/java/com/main_39/Spring/order/entity/Order.java
src/main/java/com/main_39/Spring/order/mapper/OrderMapper.java

refactor:  주문요청사항 추가, 주문 리스트, 상세 주문 응답 수정

---

build.gradle
src/main/java/com/main_39/Spring/order/controller/PaymentController.java

결제 api gradle 의존성 추가
결제 검증 컨트롤러 추가

feat: 결제 api gradle 의존성 추가, 결제 검증 컨트롤러 추가

---

src/main/java/com/main_39/Spring/order/controller/OrderController.java

refactor: 주문 테스트를 위한 카카오 객체 주석처리

---

src/main/java/com/main_39/Spring/order/dto/OrderMenuResponse.java
src/main/java/com/main_39/Spring/order/mapper/OrderMapper.java

refactor: 주문 기능 메뉴 응답에 가게id 추가

---

src/main/java/com/main_39/Spring/order/dto/OrderMenuResponse.java
src/main/java/com/main_39/Spring/order/mapper/OrderMapper.java

refactor: 주문 기능 메뉴 응답에 가게명 추가

---

src/main/java/com/main_39/Spring/order/controller/OrderController.java

refactor: 주문 기능 카카오 주석 해제

---

src/main/java/com/main_39/Spring/config/SecurityConfig.java
src/main/java/com/main_39/Spring/config/filter/JwtAuthenticationFilter.java
src/main/java/com/main_39/Spring/review/controller/ReviewController.java
src/main/java/com/main_39/Spring/review/dto/ReviewResponseDto.java
src/main/java/com/main_39/Spring/review/mapper/ReviewMapper.java

feat: 회원 식별 기능 auth필드 추가

---

src/main/java/com/main_39/Spring/member/entity/Local.java
src/main/java/com/main_39/Spring/order/controller/OrderController.java
src/main/java/com/main_39/Spring/order/entity/Order.java

feat: 로컬 회원으로도 주문 가능하게 추가

---

src/main/java/com/main_39/Spring/order/mapper/OrderMapper.java

fix: 주문 매퍼 수정

---

src/main/java/com/main_39/Spring/order/entity/Order.java

fix: fetch type 즉시로딩으로 변경

---

src/main/java/com/main_39/Spring/config/filter/JwtAuthorizationFilter.java

fix: localdetails 수정

---

src/main/java/com/main_39/Spring/order/service/OrderService.java

fix: 주문 서비스 트랜잭션 추가

---

src/main/java/com/main_39/Spring/member/entity/Users.java

remove : Users 삭제

---

src/main/java/com/main_39/Spring/menu/controller/MenuController.java
src/main/java/com/main_39/Spring/menu/service/MenuService.java
src/main/java/com/main_39/Spring/store/entity/Store.java

fix: 메뉴 삭제 기능 fix

---

src/main/java/com/main_39/Spring/comment/controller/CommentController.java
src/main/java/com/main_39/Spring/member/entity/Users.java

fix: 답글 회원 검증 로직 변경

---

src/main/java/com/main_39/Spring/comment/controller/CommentController.java
src/main/java/com/main_39/Spring/member/entity/Users.java

fix: 답글 삭제 회원 검증 로직 수정

---

src/main/java/com/main_39/Spring/review/entity/Review.java

fix: review cascadeType 제거

---

src/main/java/com/main_39/Spring/review/entity/Review.java
src/main/java/com/main_39/Spring/store/entity/Store.java

fix: review, comment cascade 제거 

---

src/main/java/com/main_39/Spring/review/entity/Review.java
src/main/java/com/main_39/Spring/store/entity/Store.java

fix: review 수정

---

src/main/java/com/main_39/Spring/comment/entity/Comment.java
src/main/java/com/main_39/Spring/review/entity/Review.java
src/main/java/com/main_39/Spring/store/entity/Store.java

commnet 삭제를 위한 review cascade 제거

fix: commnet 삭제를 위한 review cascade 제거

---

src/main/java/com/main_39/Spring/comment/entity/Comment.java
src/main/java/com/main_39/Spring/member/entity/Kakao.java
src/main/java/com/main_39/Spring/member/entity/Local.java
src/main/java/com/main_39/Spring/menu/entity/Menu.java
src/main/java/com/main_39/Spring/order/entity/Order.java
src/main/java/com/main_39/Spring/order/entity/OrderMenu.java
src/main/java/com/main_39/Spring/review/entity/Review.java
src/main/java/com/main_39/Spring/store/entity/Store.java

refactor: 엔티티 페치 타입 변경, batchSize 조절

---

src/main/java/com/main_39/Spring/comment/entity/Comment.java
src/main/java/com/main_39/Spring/member/entity/Kakao.java
src/main/java/com/main_39/Spring/member/entity/Local.java
src/main/java/com/main_39/Spring/menu/entity/Menu.java
src/main/java/com/main_39/Spring/order/entity/Order.java
src/main/java/com/main_39/Spring/order/entity/OrderMenu.java
src/main/java/com/main_39/Spring/review/entity/Review.java
src/main/java/com/main_39/Spring/store/entity/Store.java

엔티티 페치 타입 변경, batchSize 조절 revert

fix : 엔티티 페치 타입 변경, batchSize 조절 revert

---

frontend/src/components/DetailFoodList/index.js
frontend/src/components/Hoc/index.js
frontend/src/constants/api.js
frontend/src/constants/route.js
frontend/src/hooks/useDetailFoodList.js
frontend/src/hooks/useSetting.js
frontend/src/pages/FoodList/FoodDetail/index.js
frontend/src/pages/FoodTruckSetting/MenuList/index.js
frontend/src/pages/FoodTruckSetting/UpdateForm/index.js
frontend/src/pages/FoodTruckSetting/index.js
frontend/src/pages/Home/index.js
frontend/src/pages/MyPage/index.js
frontend/src/store/atoms.js

withAuth, MyPage naviate to trucksetting 기능 추가

feat: withAuth, MyPage naviate to trucksetting 기능 추가

---

src/main/java/com/main_39/Spring/menu/entity/Menu.java
src/main/java/com/main_39/Spring/order/entity/Order.java
src/main/java/com/main_39/Spring/order/entity/OrderMenu.java

refactor: 메뉴, 주문 엔티티 lazy

---

src/main/java/com/main_39/Spring/member/controller/MemberController.java
src/main/java/com/main_39/Spring/review/controller/ReviewController.java
src/main/java/com/main_39/Spring/review/service/ReviewService.java

feat: 리뷰 수정,삭제 그리고 카카오 마일리지 인증 추가

feat: 리뷰 수정,삭제 그리고 카카오 마일리지 인증 추가

---

src/main/java/com/main_39/Spring/menu/entity/Menu.java
src/main/java/com/main_39/Spring/order/entity/Order.java
src/main/java/com/main_39/Spring/order/entity/OrderMenu.java

fix: fetch 복구

---

src/main/java/com/main_39/Spring/member/controller/MemberController.java
src/main/java/com/main_39/Spring/menu/controller/MenuController.java
src/main/java/com/main_39/Spring/menu/entity/Menu.java
src/main/java/com/main_39/Spring/menu/service/MenuService.java
src/main/java/com/main_39/Spring/review/controller/ReviewController.java
src/main/java/com/main_39/Spring/review/service/ReviewService.java
src/main/java/com/main_39/Spring/store/controller/StoreController.java
src/main/java/com/main_39/Spring/store/service/StoreService.java

fix: S3이미지 저장관련 에러 수정

---

src/main/java/com/main_39/Spring/review/service/ReviewService.java
src/main/java/com/main_39/Spring/store/service/StoreService.java

한명의 사업자는 하나의 푸드트럭만 등록할 수 있습니다.

fix: 2개이상의 가게 등록 금지

---

src/main/java/com/main_39/Spring/comment/service/CommentService.java
src/main/java/com/main_39/Spring/review/entity/Review.java

refactor: 리뷰 답변id 삭제 추가

---

src/main/java/com/main_39/Spring/member/entity/Local.java
src/main/java/com/main_39/Spring/menu/entity/Menu.java
src/main/java/com/main_39/Spring/order/entity/Order.java
src/main/java/com/main_39/Spring/review/service/ReviewService.java
src/main/java/com/main_39/Spring/store/entity/Store.java
src/main/java/com/main_39/Spring/store/repository/StoreRepository.java
src/main/java/com/main_39/Spring/store/service/StoreService.java

fix: 가게 2개 이상 등록 불가 수정

---

src/main/java/com/main_39/Spring/store/entity/Store.java

refactor: 가게 일대다 orphanRemoval 옵션추가

---

frontend/src/pages/FoodTruckSetting/MenuList/index.js

메뉴 수정할때 이미지나 특정 정보만 적어도 그 정보만 갱신 수정 되도록 개선하였습니다.

feat: 메뉴수정 UX 개선

---

frontend/src/pages/FoodTruckSetting/MenuList/index.js
frontend/src/pages/FoodTruckSetting/UpdateForm/index.js
frontend/src/pages/FoodTruckSetting/index.js

가게 정보와 메뉴 수정시 모든 정보를 적지 않아도 (시스템상 이미지는 필수) 수정할수 있게 개선

feat: 가게설정 UX 개선
